kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{service.name}}-author
spec:
  revisionHistoryLimit: 3
  template:
    metadata:
       labels:
          app: {{service.name}}-author
    spec:
      containers:
        - name: {{service.name}}-author
          image: {{build.images["author/Dockerfile"]}}
          env:
            - name: APP_ENV
              value: prod
            - name: APP_SECRET
              value: f2d6e11dad33d6046f727926921fb546
            - name: DATABASE_URL
              value: mysql://root:password@mysql:3306/sulu
          resources:
            limits:
              memory: {{service.memory}}
              cpu: {{service.cpu}}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 1
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: {{service.name}}-author
spec:
  ports:
  -
    name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{service.name}}-author
