kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kubexample
spec:
  revisionHistoryLimit: 3
  template:
    metadata:
       labels:
          app: {{service.name}}
    spec:
      containers:
        - name: {{service.name}}
          image: {{build.images["application/Dockerfile"]}}
          resources:
            limits:
              memory: {{service.memory}}
              cpu: {{service.cpu}}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 1
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: {{service.name}}
spec:
  ports:
  -
    name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{service.name}}
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{service.name}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{service.name}}.localhost
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{service.name}}
          servicePort: 80
